import { defineConfig } from 'vite';
import { resolve, relative } from 'node:path';
import { readdirSync, existsSync } from 'node:fs';
import { cp, copyFile, writeFile } from 'node:fs/promises';
import { versionClassicScripts } from './tools/vite-classic-script-versioning.mjs';

const root = import.meta.dirname;

/**
 * Find every HTML page in the repository.
 *
 * This means we do NOT have to manually maintain a list of 20+ pages.
 * Any new HTML page placed under the project will automatically become
 * a Vite entry point on the next build.
 */
function findHtmlEntries(dir, baseDir = dir) {
  const entries = {};

  for (const item of readdirSync(dir, { withFileTypes: true })) {
    // Never scan generated/dependency directories.
    if (
      item.name === 'node_modules' ||
      item.name === 'dist' ||
      item.name.startsWith('.')
    ) {
      continue;
    }

    const fullPath = resolve(dir, item.name);

    if (item.isDirectory()) {
      Object.assign(entries, findHtmlEntries(fullPath, baseDir));
      continue;
    }

    if (!item.isFile() || !item.name.endsWith('.html')) {
      continue;
    }

    const relativePath = relative(baseDir, fullPath)
      .replaceAll('\\', '/');

    // Example:
    // index.html
    // pages/dashboard.html
    // pages/admin-users.html
    const key = relativePath
      .replace(/\.html$/, '')
      .replace(/[^\w]+/g, '_');

    entries[key || 'index'] = fullPath;
  }

  return entries;
}

/**
 * Some parts of the existing LinguaWave frontend use runtime URLs such as:
 *
 *   /asl_static_model/model.json
 *   /asl_motion_model/model.json
 *   ../assets/...
 *   ../js/...
 *
 * We are deliberately NOT restructuring those files yet.
 *
 * During a production build, copy the existing runtime directories into
 * dist/ so the current application can continue to resolve those URLs.
 */
/**
 * js/auth.js builds its redirect targets like this:
 *     new URL('../index.html', import.meta.url)
 * Vite treats that exact pattern as "bundle this file as an asset": it emits a
 * processed copy (dist/assets/index-<hash>.html) and rewrites the URL to point at it.
 * That copy's relative paths no longer resolve, so every login/logout/verify redirect
 * would land on a broken page. The ORIGINAL string is already correct after the build
 * (chunks live in dist/assets/, one level deep, exactly like js/), so at build time
 * only we split the path literal. Vite no longer recognises the pattern and leaves
 * it alone. Source files are not modified.
 */
const HTML_URL_PATTERN = /new\s+URL\(\s*(['"])(\.{1,2}\/[^'"]*?\.html)\1\s*,\s*import\.meta\.url\s*\)/g;

function splitHtmlUrlLiterals(code) {
  return code.replace(HTML_URL_PATTERN, (_match, quote, path) => {
    const cut = path.lastIndexOf('/') + 1;
    return `new URL(${quote}${path.slice(0, cut)}${quote} + ${quote}${path.slice(cut)}${quote}, import.meta.url)`;
  });
}

function keepHtmlUrlsAsPlainStrings() {
  const jsDir = resolve(root, 'js').replaceAll('\\', '/') + '/';
  return {
    name: 'linguawave-keep-html-urls',
    apply: 'build',
    enforce: 'pre',

    transform(code, id) {
      const file = id.split('?')[0].replaceAll('\\', '/');
      if (!file.startsWith(jsDir) || !/\.m?js$/.test(file)) return null;
      const out = splitHtmlUrlLiterals(code);
      return out === code ? null : { code: out, map: null };
    },
  };
}

/**
 * Hashed Vite output (assets/<name>-<8 char hash>.js|css|woff2) can never change
 * under the same URL, so browsers may keep it for a year. Everything else keeps
 * the root .htaccess rule (no-cache, must-revalidate). Scoped to dist/assets/ and to
 * the hash pattern on purpose: unhashed files like js/camera-tips-reminder.js must
 * NOT match.
 */
const ASSETS_HTACCESS = `# Generated by vite.config.js - do not edit by hand.
<IfModule mod_headers.c>
  <FilesMatch "-[A-Za-z0-9_-]{8}\\.(js|css|woff2)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>
</IfModule>
`;

/**
 * After Vite has written dist/:
 *  1. copy the runtime folders Vite does not know about (classic scripts, assets, models)
 *  2. copy the root .htaccess so the cache headers ship with the deploy
 *  3. write dist/assets/.htaccess (long cache for hashed files only)
 *  4. add ?v=<content hash> to every classic <script src> in the built pages
 */
function linguawaveRuntimeFiles() {
  return {
    name: 'linguawave-runtime-files',
    apply: 'build',

    async closeBundle() {
      const dist = resolve(root, 'dist');

      // Safety net: Vite must never emit HTML into assets/ (see keepHtmlUrlsAsPlainStrings).
      const strayHtml = existsSync(resolve(dist, 'assets'))
        ? readdirSync(resolve(dist, 'assets')).filter((name) => name.endsWith('.html'))
        : [];
      if (strayHtml.length) {
        throw new Error(
          `[linguawave] Vite emitted HTML into dist/assets/: ${strayHtml.join(', ')}. ` +
          `Some script contains new URL('<page>.html', import.meta.url), which breaks redirects.`
        );
      }
      const directories = [
        'js',
        'assets',
        'asl_static_model',
        'asl_motion_model',
      ];

      await Promise.all(
        directories.map((directory) =>
          cp(resolve(root, directory), resolve(dist, directory), {
            recursive: true,
            force: true,
          })
        )
      );

      if (existsSync(resolve(root, '.htaccess'))) {
        await copyFile(resolve(root, '.htaccess'), resolve(dist, '.htaccess'));
      } else {
        console.warn('[linguawave] no root .htaccess found - dist/ will ship without cache headers');
      }
      await writeFile(resolve(dist, 'assets', '.htaccess'), ASSETS_HTACCESS);

      const stats = versionClassicScripts(dist);
      console.log(
        `[linguawave] versioned ${stats.tags} classic <script> tags ` +
        `(${stats.files.size} unique files) across ${stats.pages} pages`
      );
      if (stats.missing.length) {
        console.warn(
          `[linguawave] ${stats.missing.length} script src(s) not found in dist/ and left unversioned:\n  ` +
          [...new Set(stats.missing)].join('\n  ')
        );
      }
    },
  };
}

export default defineConfig({
  root,

  // This is still a normal multi-page website, not an SPA.
  appType: 'mpa',

  // Keep generated URLs relative to each HTML page.
  base: './',

  build: {
    outDir: 'dist',
    emptyOutDir: true,

    rollupOptions: {
      input: findHtmlEntries(root),
    },
  },

  plugins: [
    keepHtmlUrlsAsPlainStrings(),
    linguawaveRuntimeFiles(),
  ],
});
